### ISSUE TITLE
how to quit

### ISSUE THREAD

**Issue by LordsTrident** [MESYETI/yedit#2]
how do i quit yedit help

**Comment by MESYETI** [comment]
press control c but in next version i change to control q

**Comment by LordsTrident** [comment]
ctrl c is not working it just prints out  ^C

**Comment by MrMyth152346** [comment]
add windows support

**Comment by MESYETI** [comment]
> add windows support

how

**Comment by MESYETI** [comment]
> ctrl c is not working it just prints out  ^C

oh no can you give me your computer so i can debug it

**Comment by LordsTrident** [comment]
> > add windows support
> 
> how

ncurses isnt for windows but there is PDCurses which is for windows
